services:
  scoresapi:
    build:
      context: ScoresApi
      dockerfile: Dockerfile
    ports:
      - "5195:5195"
    depends_on:
      - scoresdb
    environment:
      - REDIS_CONNECTION_STRING=scoresdb:6379

  scoresdb:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
